### ISSUE TITLE
2496 capability 

### ISSUE THREAD

**Issue by omnipop** [muammar/mkchromecast#11]
Hi there,

I am new to this site, but wanted to thank you for developing this software. It works well.

I have the Chromecast audio, which can stream at 24 bit 96K resolution. The app goes up to 48 K and does not indicate the bit rate in flac or wav. If the app needs improvement , it is that. 

Thank you again

**Comment by muammar** [comment]
@omnipop thanks for your message. It turns out that `ffmpeg` does not have any option to change the bitrate for the  `wav` code, AFAICR. If I understand correctly, in ffmpeg the bitrate for wav is `1411 kb/s`, while flac is `~900 kb/s`. And the `'-acodec', 'pcm_s24le'` option assures the `24bits`. You can verify that when launching `mkchromecast` with the ` --debug` flag. 

As for the `96K`, I will modify the code so that it accepts it. However, note that if your audio source is "low", let's suppose `44.1K`, [re-sampling  it to `48k` or `96k` is not recommended](https://productforums.google.com/forum/?hl=en-GB#!topic/chromecast/k6JZRM2TUco;context-place=topicsearchin/chromecast/category$3Acasting-from-a-supported-app).

**Comment by muammar** [comment]
I think it is done. Commit ec10bfba207fe9caed823081480a1037c67bc37c introduces your request. Casting with `wav + 96k` or `flac + 96k` should reach the `24bits/96k` google cast audio capability.
