### ISSUE TITLE
Playing from pipe/stream instead of hooking into soundsystem

### ISSUE THREAD

**Issue by quite** [muammar/mkchromecast#19]
I realize that my use-case of mkchromecast mostly would be to move the sound of mpd https://www.musicpd.org/ to the chromecast-audio. All this hooking up to pulseaudio or alsa would not really be necessary, perhaps rather unwanted. I may actually want to hear other sounds from the speakers on the computer.

So, having mkchromecast reading directly from a pipe or a http stream perhaps would make more sense. I assume the data here being already ogg, mp3 or so is not a problem (not really any overhead), since mkchromecast is doing the encoding anyway. What do you think?

**Comment by muammar** [comment]
Reading from a a pipe or stream is totally feasible. However, reading a http stream would be much more easy for the moments. I was thinking in providing a flag `--stream-url` that users can pass to mkchromecast so that the audio (or video) can be played. Something like:

```
mkchromecast --stream-url https://ip:port/something -c ogg
```

I will implement this and come back to you so that you can test it. I suppose that configuring a HTTP streaming server `type "httpd"`  in `mpd.conf` would do the trick.

As for the pipe from mpd, it's been a while since I don't use mpd myself. But if you could provide a working config file that do pipe I can work with it. In any case, I will read a bit more about it.

**Comment by quite** [comment]
Yes, `"httpd"` it is, and I already have that set up for streaming reasons. Ready to test!

**Comment by muammar** [comment]
@quite it is working. Update the `alsa` branch and do for instance:

```
python mkchromecast.py --stream-url http://192.99.131.205:8000/pvfm1.ogg -c ogg --volume
```
So you can pass your ogg stream coming from mpd, and it should work. You always have to use the `-c` flag to specify the codec. Tell me if it works. For me it is working great, this is very fun.

**Comment by quite** [comment]
Indeed, it's working OK. Would it make sense to call the option perhaps `--source-url` instead?

**Comment by muammar** [comment]
I can change it to that, I agree. Thanks for reporting back.

**Comment by muammar** [comment]
Now it is done. Please, feel free to close this report if you don't find anything else wrong :). Cheers.
