### ISSUE TITLE
Can't set desired bitrate for ogg via cmdl defaults to 500k

### ISSUE THREAD

**Issue by ao-il** [muammar/mkchromecast#21]
I use mkchromecast with alsa but it seems it cannot set bitrate for ogg and always defaults to 500k max bitrate no matter what it's given. Also, the latency is much higher than 4s. 

Does the cast device use the same settings and sample rate for playback? 

Thanks in advance for your help, and btw good job!

**Comment by muammar** [comment]
@ao-il thanks for your report because in that way I can keep improving **mkchromecast**. Can you tell me if it happens just with `ogg` codec, or also with `mp3` and `acc`?.

Regarding latency, it is a very hard thing. I recently changed of ISP where I live, and with the new WIFI router I had an improvement from `8s ` to just `4s` lag. I then decided to remove the `-re` flag from `ffmpeg` encoder backed and it improved to `3s` lag in  my case. I am thinking of ways to improve this (I am for instance implementing `gstreamer` pipes to capture audio and see if it gets any better). I have realised that when I using **mkchromecast** in macOS, the `node` server I am using to capture and encode is much more efficient in the sense that lag is below `2s`. For sure this problem you are getting of not being able to change `500k` bitrate will request more from your router!.

**Comment by ao-il** [comment]
I just tried mp3 and it works, but my files are ogg and would like to use the same format to stream. I realize that with audacity you can't set bitrate for ogg but instead you specify a quality number ranging from 1-10, where 9=320. Do you think I can use -q 9 instead? This is because ogg uses VBR. Regarding the sample rate, do you the cast device resamples? Cuz in the asoundrc, I saw you commented out 44100. I uncommented that because my files are not 48000 but the latter. Hope the device does not up resample to 48000?

**Comment by muammar** [comment]
@ao-il I have pushed a commit in  the `devel` branch that should fix this problem. For the moments you have to always set bitrate with integer numbers with mkchromecast. I could work to implement a quality flag maybe. 

By default the sample rate of the app is at 44100. You may modify it if you want, and as far as I can tell the google cast devices do not resample. That was a bug they fixed. Could you check that commit https://github.com/muammar/mkchromecast/commit/b010da5ae9089e9c8feb0d2ccd97cb34b6905cf4 fix your problem?.

Thanks.

**Comment by ao-il** [comment]
It now works to set 320 for ogg. Thanks alot!
