### ISSUE TITLE
Can´t cast to sonos connected by LAN - No devices found

### ISSUE THREAD

**Issue by piberry** [muammar/mkchromecast#210]
Hi!
I tried a couple of times to make mkchromcast work with my sonos Play 1 speakers but i always get "No device found" when i start mkchromecast. Everything seems to be setup right and i installed soco.
I´m using a raspberry pi 3 with raspbian stretch.
The sonos speakers are connected by LAN, could this cause the issue?
I tried to unpair them and put the WLAN back on  for testing but failed in the first place.  So i´m asking before i waste more time on this.

**Comment by muammar** [comment]
Hi @piberry. 

I have Play 1 at home, too. It is connected with Wifi. Let me try tonight branching it to my LAN and see if that would cause a problem?

I think someone mentioned the other day that mkchromecast was just working with single speakers but not groups of them.  I unfortunately cannot try to solve that because I just own 1 speaker.

**Comment by muammar** [comment]
Hi, I connected my laptop to my LAN, and I can stream to sonos without any problem. 

![screenshot from 2018-10-13 19-01-48](https://user-images.githubusercontent.com/954209/46910878-9292e580-cf1a-11e8-82c7-1511b3a82cb3.png)

Were you able to solve this issue?

**Comment by muammar** [comment]
I cannot reproduce this. Please, feel free to reopen this.

**Comment by muammar** [comment]
I've updated to pip3 in the documentation now. I am not supporting Python2 anymore!
