### ISSUE TITLE
Can't connect to Chromecast Audio

### ISSUE THREAD

**Issue by scratchmaster2** [muammar/mkchromecast#41]
Hi there, I'm using a Macbook Pro running Mac OS 10.12.2 (Sierra) - there is an issue when I try to cast audio sometimes. I have multiple chromecast devices in my home (a chromecast audio, a chromecast and a smart TV). I can cast audio to the TV devices fine (the chromecast and the smart TV) but when I try to cast to the chromecast audio device it invariably connects to two devices at the same time. This then means that I'm unable to hear anything from the chromecast audio. I've taken a screenshot here:

<img width="888" alt="screen shot 2017-01-21 at 12 17 03" src="https://cloud.githubusercontent.com/assets/25265120/22174332/b2114858-dfd3-11e6-80a6-e910d508f766.png">

**Comment by muammar** [comment]
Thanks for your report. I have fixed it here https://github.com/muammar/mkchromecast/commit/719fde94e271f97a2047e84b56d7603a5d8cde09. Could you try using the git repository to run mkchromecast and check if the problem is gone? 

I have been unable to build the macOS app recently: https://github.com/muammar/mkchromecast/issues/36.

**Comment by scratchmaster2** [comment]
I'm a newbie to github. Just came on to report the problem. Can you point me in the direction of resources to figure out how to do this? thanks

**Comment by muammar** [comment]
>I'm a newbie to github. Just came on to report the problem. Can you point me in the direction of resources to figure out how to do this? thanks

Thanks for wanting to try this. You can follow instructions here:

https://github.com/muammar/mkchromecast/wiki/macOS-standalone-app

To follow those instructions, you only have to open the terminal and copy and paste each of the commands in each step (sorry if you are already familiar with using the terminal). At the end of the process, there will be a `dist` directory containing the macOS app.

If you have any problem, please do not hesitate to write back!.

**Comment by scratchmaster2** [comment]
Hey, thanks for that. I just did it but I still have the same issue...

**Comment by muammar** [comment]
> Hey, thanks for that. I just did it but I still have the same issue...

Thank you. I have tested it on my macOs, and you are absolutely right. In Linux I know it is fine. Let me try to fix this.

**Comment by muammar** [comment]
I had a little of time to day to intent to fix this issue. Can you try the latest commit I have pushed to `devel`?. The only problem to be solved (if the fix is correct) would be with the systray showing two checked google cast devices. But under the hood would be fine. I would be glad if you could let me know if it is working.

**Comment by muammar** [comment]
I think this is fixed. Please reopen the issue if you think it is not solved in latest version available in git.
