### ISSUE TITLE
OS X lossless support

### ISSUE THREAD

**Issue by skijash** [muammar/mkchromecast#58]
Hello,
I installed mkchromecast and ffmpeg with all the options you proposed in the docs. When I open the preferences panel, only mp3 is available.
Do I need to install anything else?

**Comment by muammar** [comment]
No, that should be enough. How did you install ffmpeg?.

**Comment by skijash** [comment]
brew install ffmpeg --with-fdk-aac --with-sdl2 --with-freetype
--with-libass --with-libquvi --with-libvorbis --with-libvpx
--with-opus --with-x265

Restarted mkchromecast afterwards, still has only mp3 as an option.

**Comment by muammar** [comment]
That should be enough. Are you using the application from sources or from the macOS app?

**Comment by skijash** [comment]
Installed with brew cask

**Comment by skijash** [comment]
v0.3.6

**Comment by muammar** [comment]
Can you paste the output of `which ffmpeg` from your terminal, please?.

**Comment by skijash** [comment]
~ which ffmpeg
/usr/local/bin/ffmpeg

**Comment by muammar** [comment]
In my case:

```
muammar@zarathustra ~
  % which ffmpeg                                                                                                                                       !10265
/usr/local/bin/ffmpeg
```

<img width="1280" alt="screen shot 2017-04-16 at 13 18 10" src="https://cloud.githubusercontent.com/assets/954209/25072851/2bba1cf0-22a7-11e7-9c06-68abf51ce75a.png">
<img width="1280" alt="screen shot 2017-04-16 at 13 18 44" src="https://cloud.githubusercontent.com/assets/954209/25072856/3d88517c-22a7-11e7-9777-e311ef44fcc6.png">

Would you like to test the application from sources, or [create an app](https://github.com/muammar/mkchromecast/wiki/macOS-standalone-app) by yourself?. I also could create one with latest `HEAD` in master so that you can use it and let me know. Currently, it is not possible for me to build a standalone app to distribute. `py2app` + `pyqt5` seems broken.

**Comment by skijash** [comment]
Ok, I'll test it and let you know what happened.

**Comment by skijash** [comment]
Works now, I haven't changed the backend until now, I thought it should be node :-/

**Comment by muammar** [comment]
No problem :). Glad it is working now.
