### ISSUE TITLE
apt not working:

### ISSUE THREAD

**Issue by benyanke** [muammar/mkchromecast#74]
I tried running `sudo apt-get install -y mkchromecast` on my ubuntu 16.04.2 LTS box, and it's unable to locate the package. What am I missing?

**Comment by muammar** [comment]
**mkchromecast**  is not available for `16.04`. This is its availability in Ubuntu: https://packages.ubuntu.com/search?keywords=mkchromecast. Maybe you can try installing the packages from `16.10`?.

**Comment by benyanke** [comment]
What's the best way to do that? Is there a PPA to add or something along those lines?

**Comment by muammar** [comment]
On Tue, Jun 13, 2017 at 5:19 PM, Ben Yanke <notifications@github.com> wrote:
>
> What's the best way to do that? Is there a PPA to add or something along those lines?

I don't have a PPA for it because I am Debian developer and I just
want to maintain the application in one site. I would just point to
16.10 in `/etc/apt/sources.list` temporarily, and do `apt-get update`
and then install mkchromecast. That shouldn't be that bad, but be
careful to not pull any weird dependency that could lead to breaking
your installation. After that, you delete the `16.10` repo lines from
your `sources.list`. Then, you can just download the versions I
publish in Github. If for some reason when you do apt-get install you
get something more than what I show in the list below, something weird
could happen:

```
Depends: python:any (>= 2.7.5-5~), python-flask, python-pychromecast,
python-psutil, vorbis-tools (>= 1.4.0), sox (>= 14.4.1), lame (>=
3.99.0), flac (>=  1.3.0), python-pyqt5, youtube-dl, nodejs,
gir1.2-notify-0.7
```





-- 
Muammar El Khatib.
http://muammar.me
