### ISSUE TITLE
Preserve audio fidelity

### ISSUE THREAD

**Issue by ao-il** [muammar/mkchromecast#81]
Is this possible? Is there a way to verify that all bits arrive at the client? Anyone playing 16/44.1 aka CD or 24/96 aka hi res and enjoying hi-fi (better than cd quality) music?

**Comment by muammar** [comment]
You could try the following:

1.  Launch the application with `ffmpeg` using the desired quality. 
2. `ps aux |grep ffmpeg` to catch the command being used. 
3. Instead of piping with `ffmpeg`, dump to a file. 
4. Verify the quality of the file. 

The same quality of that file is the data that is being sent by the flask server. Does it make sense?.

**Comment by ao-il** [comment]
Thanks, but no, I meant to check the quality at the client side since that's what I hear.

**Comment by muammar** [comment]
I asked myself the same some time ago. A time ago with some other user, we checked the quality of the streams built with `ffmpeg` in Mkchromecast. We verified they were created correctly, and that's why I trust that `python-flask` webserver si sending the correct data with the correct `mtype`.

I also searched in `pychromecast`  and it only has this function [pychromecast/dial.py#L38](https://github.com/balloob/pychromecast/blob/e39fa31029459784b2e78b5a68efddedc7bb5c42/pychromecast/dial.py#L38) to get the status.  Have you asked in a[ chromecast official forum](https://productforums.google.com/forum/#!forum/chromecast)?. It would be very interesting to know how to do know what the chromecast is playing.

**Comment by ao-il** [comment]
I have verified that ffmpeg is encoding bit perfect, but I hear sounds like something choked. It could be that the sender is sending too fast and network can't keep up. You could view the packet flow with `tcpdump` and see some are dropped because of this. Yes, would be nice if one could get help from one of those forums.

**Comment by ao-il** [comment]
I have just discovered that the chromecast plugin/cast feature for chromium is using UDP to cast audio, and there is no delay at all. So, chromecast supports UDP.

**Comment by muammar** [comment]
You mean if I use a `udp://localhost:5000` that would work?. I will try!.

**Comment by ao-il** [comment]
I'm not sure how it is done but you could try that. I only inspected the packets and saw they were UDP.
